export const tempArrayFinished: string[] = [];
export const tempArrayWatching: string[] = [];
export const tempArrayWatchlist: string[] = [];

export const animeList: string[] = [
  'A Ben Mao',
  'A Brightening Life',
  'A Day Before Us',
  'A Kite',
  'A Log Day Of Timbre',
  'A New Journey',
  'A Piece of Phantasmagoria',
  "A Sea Doesn't Tell Much",
  'A Smart Experiment',
  'A Tang Qi Yu',
  'A Woman In A Fashion Building',
  'A-Channel',
  'A-Channel+smile',
  'A-Channel: +A-Channel',
  'A-Channel: Nabe wo Tabeyou',
  'A-Girl',
  'A-jang.com',
  'A-Ko The Versus',
  'A-Size Classmate',
  'A.D. Police (TV)',
  'A.F.',
  'A.I.C.O.: Incarnation',
  'A.LI.CE',
  'A3! Season Autumn & Winter',
  'A3! Season Spring & Summer',
  'Aa / ii',
  'Aa Harimanada',
  'Aa! Megami-sama!',
  'Aa! Megami-sama! (2011)',
  'Aa! Megami-sama! (TV)',
  'Aa! Megami-sama! (TV) Specials',
  'Aa! Megami-sama! Movie',
  'Aa! Megami-sama!: Chichaitte Koto wa Benri da ne',
  'Aa! Megami-sama!: Sorezore no Tsubasa',
  'Aa! Megami-sama!: Sorezore no Tsubasa Specials',
  'Aa! Megami-sama!: Tatakau Tsubasa',
  'AAA de Ikou!!: Yuuna & Akiko',
  'Aachi wa Ssipak',
  'Abarenbou Rikishi!! Matsutarou',
  'Abashiri Ikka',
  'ABC Tenkiyohou',
  'Abciee Shuugyou Nikki',
  'Abe George Kattobi Seishun Ki: Shibuya Honky Tonk',
  'Abenobashi Mahou☆Shoutengai',
  'Absolute Duo',
  'Abstract feat. Alkama',
  'Abu Shui Qian Gushi',
  'Abunai Sisters: Koko & Mika',
  'ACCA: 13-ku Kansatsu-ka',
  'ACCA: 13-ku Kansatsu-ka - Regards',
  'ACCA: 13-ku Kansatsu-ka Specials',
  'Accel World',
  'Accel World EX',
  'Accel World: Acchel World',
  'Accel World: Infinite∞Burst',
  'Accelerando: Datenshi-tachi no Sasayaki',
  'Acchi Kocchi',
  'Acchi Kocchi (TV)',
  'Acchi Kocchi (TV): Place=Princess',
  'Ace wo Nerae!',
  'Ace wo Nerae! (1979)',
  'Ace wo Nerae! 2',
  'Ace wo Nerae!: Final Stage',
  'Acerola-chan',
  'Action Heroine Cheer Fruits',
  'Active Raid: Kidou Kyoushuushitsu Dai Hachi Gakari',
  'Active Raid: Kidou Kyoushuushitsu Dai Hachi Gakari 2nd',
  'Actors: Songs Connection',
  'Ad Lib Anime Kenkyuujo',
  'AD Police',
  'Adachi to Shimamura',
  'Adachi to Shimamura Mini Anime',
  'Adachi-ga Hara',
  'Adesugata Mahou no Sannin Musume',
  'Adobe Student and Teacher Edition',
  'Advancer Tina',
  'Adventures in Beauty Wonderland',
  'AEIOUdan: Douro no Tadashii Watari Kata',
  'Aerover: Pinigseuui Buhwal',
  'Aerover: Seupeiseu Drone Gwihwan',
  'Aesop Douwa',
  "Aesop's World",
  'Afghanistan Paghman-mura no Monogatari: Boku no Mura ni Circus ga Kita',
  'Afghanistan Paghman-mura no Monogatari: Sekaiichi Utsukushii Boku no Mura',
  'Africa no Salaryman',
  'Africa no Salaryman (TV)',
  'Afro Samurai',
  'Afro Samurai Movie',
  'Afro Samurai Pilot',
  'Afro Samurai: Resurrection',
  'Afro-Ken',
  'After School',
  'After War Gundam X',
  'After... The Animation',
  'Afureko! AR',
  'Against',
  'Agatha Christie no Meitantei Poirot to Marple',
  'Age Man to Fuku Chin',
  'Age of Obscure: Boubaku Jidai',
  'Aggressive Retsuko',
  'Aggressive Retsuko (ONA)',
  'Aggressive Retsuko (ONA) 2nd Season',
  'Aggressive Retsuko (ONA) 3rd Season',
  'Aggressive Retsuko (ONA) 4th Season',
  'Aggressive Retsuko: We Wish You a Metal Christmas',
  'Agigongryong Doolie',
  'Agigongryong Doolie (1988)',
  'Agigongryong Doolie (2009)',
  'Agigongryong Doolie (Movie)',
  'Agukaru',
  'Agukaru: Play with Ibaraki-hen',
  'Agukaru: Play with Ibaraki-hen Episode 0',
  'Aguu: Tensai Ningyou',
  'Ahiru no Ko',
  'Ahiru no Otegara',
  'Ahiru no Pekkle no Ahiru no Drakestail',
  'Ahiru no Pekkle no Aladdin to Mahou no Lamp',
  'Ahiru no Pekkle no Hihou wo Sagase',
  'Ahiru no Pekkle no Minikui Ahiru no Ko',
  'Ahiru no Pekkle no Sindbad no Bouken',
  'Ahiru no Pekkle no Suieitaikai wa Oosawagi',
  'Ahiru no Sora',
  'Ahiru Rikusentai',
  'Aho Girl',
  'Ai',
  'Ai (ONA)',
  'Ai City',
  'Ai Doll',
  'Ai Mai! Moe Can Change!',
  'Ai Monogatari: 9 Love Stories',
  'Ai no Gakkou Cuore Monogatari',
  'Ai no Katachi: Ecchi na Onnanoko wa Kirai... Desu ka?',
  'Ai no Kiseki: Doctor Norman Monogatari',
  'Ai no Kusabi',
  'Ai no Kusabi (2012)',
  'Ai no Senshi Rainbowman',
  'Ai no Utagoe wo Kikasete',
];

export const mangaList: string[] = [];
