export const tempArrayFinished: string[] = [];
export const tempArrayWatching: string[] = [];
export const tempArrayWatchlist: string[] = [];

export const animeList: string[] = [
  'A Ben Mao',
  'A Brightening Life',
  'A Day Before Us',
  'A Kite',
  'A Log Day Of Timbre',
  'A New Journey',
  'A Piece of Phantasmagoria',
  "A Sea Doesn't Tell Much",
  'A Smart Experiment',
  'A Tang Qi Yu',
  'A Woman In A Fashion Building',
  'A-Channel',
  'A-Channel+smile',
  'A-Channel: +A-Channel',
  'A-Channel: Nabe wo Tabeyou',
  'A-Girl',
  'A-jang.com',
  'A-Ko The Versus',
  'A-Size Classmate',
  'A.D. Police (TV)',
  'A.F.',
  'A.I.C.O.: Incarnation',
  'A.LI.CE',
  'A3! Season Autumn & Winter',
  'A3! Season Spring & Summer',
  'Aa / ii',
  'Aa Harimanada',
  'Aa! Megami-sama!',
  'Aa! Megami-sama! (2011)',
  'Aa! Megami-sama! (TV)',
  'Aa! Megami-sama! (TV) Specials',
  'Aa! Megami-sama! Movie',
  'Aa! Megami-sama!: Chichaitte Koto wa Benri da ne',
  'Aa! Megami-sama!: Sorezore no Tsubasa',
  'Aa! Megami-sama!: Sorezore no Tsubasa Specials',
  'Aa! Megami-sama!: Tatakau Tsubasa',
  'AAA de Ikou!!: Yuuna & Akiko',
  'Aachi wa Ssipak',
  'Abarenbou Rikishi!! Matsutarou',
  'Abashiri Ikka',
  'ABC Tenkiyohou',
  'Abciee Shuugyou Nikki',
  'Abe George Kattobi Seishun Ki: Shibuya Honky Tonk',
  'Abenobashi Mahou☆Shoutengai',
  'Absolute Duo',
  'Abstract feat. Alkama',
  'Abu Shui Qian Gushi',
  'Abunai Sisters: Koko & Mika',
  'ACCA: 13-ku Kansatsu-ka',
  'ACCA: 13-ku Kansatsu-ka - Regards',
  'ACCA: 13-ku Kansatsu-ka Specials',
  'Accel World',
  'Accel World EX',
  'Accel World: Acchel World',
  'Accel World: Infinite∞Burst',
  'Accelerando: Datenshi-tachi no Sasayaki',
  'Acchi Kocchi',
  'Acchi Kocchi (TV)',
  'Acchi Kocchi (TV): Place=Princess',
  'Ace wo Nerae!',
  'Ace wo Nerae! (1979)',
  'Ace wo Nerae! 2',
  'Ace wo Nerae!: Final Stage',
  'Acerola-chan',
  'Action Heroine Cheer Fruits',
  'Active Raid: Kidou Kyoushuushitsu Dai Hachi Gakari',
  'Active Raid: Kidou Kyoushuushitsu Dai Hachi Gakari 2nd',
  'Actors: Songs Connection',
  'Ad Lib Anime Kenkyuujo',
  'AD Police',
  'Adachi to Shimamura',
  'Adachi to Shimamura Mini Anime',
  'Adachi-ga Hara',
  'Adesugata Mahou no Sannin Musume',
  'Adobe Student and Teacher Edition',
  'Advancer Tina',
  'Adventures in Beauty Wonderland',
  'AEIOUdan: Douro no Tadashii Watari Kata',
  'Aerover: Pinigseuui Buhwal',
  'Aerover: Seupeiseu Drone Gwihwan',
  'Aesop Douwa',
  "Aesop's World",
  'Afghanistan Paghman-mura no Monogatari: Boku no Mura ni Circus ga Kita',
  'Afghanistan Paghman-mura no Monogatari: Sekaiichi Utsukushii Boku no Mura',
  'Africa no Salaryman',
  'Africa no Salaryman (TV)',
  'Afro Samurai',
  'Afro Samurai Movie',
  'Afro Samurai Pilot',
  'Afro Samurai: Resurrection',
  'Afro-Ken',
  'After School',
  'After War Gundam X',
  'After... The Animation',
  'Afureko! AR',
  'Against',
  'Agatha Christie no Meitantei Poirot to Marple',
  'Age Man to Fuku Chin',
  'Age of Obscure: Boubaku Jidai',
  'Aggressive Retsuko',
  'Aggressive Retsuko (ONA)',
  'Aggressive Retsuko (ONA) 2nd Season',
  'Aggressive Retsuko (ONA) 3rd Season',
  'Aggressive Retsuko (ONA) 4th Season',
  'Aggressive Retsuko: We Wish You a Metal Christmas',
  'Agigongryong Doolie',
  'Agigongryong Doolie (1988)',
  'Agigongryong Doolie (2009)',
  'Agigongryong Doolie (Movie)',
  'Agukaru',
  'Agukaru: Play with Ibaraki-hen',
  'Agukaru: Play with Ibaraki-hen Episode 0',
  'Aguu: Tensai Ningyou',
  'Ahiru no Ko',
  'Ahiru no Otegara',
  'Ahiru no Pekkle no Ahiru no Drakestail',
  'Ahiru no Pekkle no Aladdin to Mahou no Lamp',
  'Ahiru no Pekkle no Hihou wo Sagase',
  'Ahiru no Pekkle no Minikui Ahiru no Ko',
  'Ahiru no Pekkle no Sindbad no Bouken',
  'Ahiru no Pekkle no Suieitaikai wa Oosawagi',
  'Ahiru no Sora',
  'Ahiru Rikusentai',
  'Aho Girl',
  'Ai',
  'Ai (ONA)',
  'Ai City',
  'Ai Doll',
  'Ai Mai! Moe Can Change!',
  'Ai Monogatari: 9 Love Stories',
  'Ai no Gakkou Cuore Monogatari',
  'Ai no Katachi: Ecchi na Onnanoko wa Kirai... Desu ka?',
  'Ai no Kiseki: Doctor Norman Monogatari',
  'Ai no Kusabi',
  'Ai no Kusabi (2012)',
  'Ai no Senshi Rainbowman',
  'Ai no Utagoe wo Kikasete',
  'Ai no Wakakusa Monogatari',
  'Ai no Wakakusa Monogatari Special',
  'Ai no Wakakusa Yama Monogatari',
  'Ai Shimai 2: Futari no Kajitsu',
  'Ai Shimai Tsubomi... Kegashite Kudasai',
  'Ai Shimai: Futari no Kajitsu',
  'Ai Shoujo Pollyanna Story',
  'Ai Shoujo Pollyanna Story Specials',
  'Ai Sky Tree 21',
  'Ai Tenchi Muyou!',
  'Ai Tenshi Densetsu Wedding Peach',
  'Ai Tenshi Densetsu Wedding Peach DX',
  'Ai Tenshi Densetsu Wedding Peach Specials',
  'Ai to Ken no Camelot: Mangaka Marina Time Slip Jiken',
  'Ai to Shi',
  'Ai to Yuuki no Pig Girl Tonde Buurin',
  'Ai wa Kagi no Kazu dake... Fuuzoku Mansion',
  'Ai wa KAT-TUN',
  'Ai wo Komete',
  'Ai Yori Aoshi',
  'Ai Yori Aoshi: Enishi',
  'Ai Yori Aoshi: Enishi - Miyuki',
  'Ai Yori Aoshi: Yumegatari',
  'Ai Zai Xiyuan Qian',
  'Ai Zai Xiyuan Qian 2nd Season',
  'Aibeya The Animation',
  'Aigan Kaijuu',
  'Aihime Megohime',
  'AIKa',
  'AIKa R-16: Virgin Mission',
  'AIKa Zero',
  'AIKa Zero Picture Drama',
  'Aika-chan no Chikyuu',
  'AIKa: Special Trial',
  'Aikagi The Animation',
  'Aikatsu Friends!',
  'Aikatsu Friends!: Kagayaki no Jewel',
  'Aikatsu on Parade!',
  'Aikatsu on Parade! (ONA)',
  'Aikatsu Planet!',
  'Aikatsu Stars!',
  'Aikatsu Stars! Movie',
  'Aikatsu!',
  'Aikatsu! Movie',
  'Aikatsu! Music Award: Minna de Shou wo MoracchaimaShow!',
  'Aikatsu!: Dai Starmiya Ichigo Matsuri Zenyasai!!',
  'Aikatsu!: Nerawareta Mahou no Aikatsu! Card',
  'Ail Maniax: Inma Seifukugari & Majogari no Yoru ni',
  'Aioi Ai oi',
  'Air',
  'Air Gear',
  'Air Gear Special',
  'Air Gear: Kuro no Hane to Nemuri no Mori - Break on the Sky',
  'Air in Summer',
  'Air Master',
  'Air Movie',
  'Air Recap',
  'Airs',
  'Aisai Nikki',
  'Aisei Tenshi Love Mary: Akusei Jutai - The Animation',
  'Aiseki Mogol Girl',
  'Aishen Qiaokeli-ing...',
  'Aishen Qiaokeli-ing... II',
  'Aishen Qiaokeli-ing: Wanjie Jinian',
  'Aishite Knight',
  'Aishiteru yo McCrea: McCrea no Koutsuu Anzen',
  'Aishiteruze Baby★★',
  'Aitata Bocchi',
  'Aitsu to Lullaby: Suiyobi no Cinderella',
  'AIUEO Anime Sekai no Douwa: Aesop Monogatari Anime Series',
  'Aiura',
  'Ajimu: Kaigan Monogatari',
  'Ajin',
  'Ajin 2nd Season',
  'Ajin 2nd Season OVA',
  'Ajin OVA',
  'Ajin Part 1: Shoudou',
  'Ajin Part 2: Shoutotsu',
  'Ajin Part 3: Shougeki',
  'Ajin Senshi',
  'Ajisai no Chiru Koro ni OVA',
  'Ajisai no Uta',
  'Ajjishin da Tsunami wa? Jibun no Inochi wa Jibun de Mamoru',
  'Akachan Honbuchou',
  'Akachan to Boku',
  'Akadou Suzunosuke',
  'Akagaki Genzou: Tokuri no Wakare',
  'Akagami no Shirayuki-hime',
  'Akagami no Shirayuki-hime 2nd Season',
  'Akagami no Shirayuki-hime: Nandemonai Takaramono, Kono Page',
  'Akage no Anne',
  'Akage no Anne Specials',
  'Akage no Anne: Green Gables e no Michi',
  'Akahori Gedou Hour Rabuge',
  'Akai Hayate',
  'Akai Ito',
  'Akai Kiba: Blue Sonnet',
  'Akai Koudan Zillion',
  'Akai Koudan Zillion Recaps',
  'Akai Koudan Zillion: Utahime Yakyoku',
  'Akai Kutsu! Onnanoko!',
  'Akai Shouzou: Char, Soshite Frontal e',
  'Akakichi no Eleven',
  'AkaKill! Gekijou',
  'Akame ga Kill!',
  'Akane Maniax',
  'Akane-chan',
  'Akaneiro ni Somaru Saka',
  'Akaneiro ni Somaru Saka: Hardcore',
  'Akanesasu Shoujo',
  'Akashic Re:cords',
  'Akatsuki no Yona',
  'Akatsuki no Yona OVA',
  'Akazukin Chacha',
  'Akazukin Chacha OVA',
  'Akazukin Chanto Manabou! Koutsuu Rule',
  'Akazukin to Kenkou',
  'AKB0048',
  'AKB0048: Next Stage',
  'AKB48 Stage Fighter',
  'Akebi no Hana: Maho',
  'Akebi-chan no Sailor-fuku',
  'Aki no Kanade',
  'Aki no Puzzle',
  'Aki-Sora',
  'Aki-Sora: Yume no Naka',
  "Akiba's Trip The Animation",
  'Akiba-chan',
  'Akibakei Kanojo',
  'Akichi Asobi: Playground',
  'Akihabara Dennou-gumi',
];

export const mangaList: string[] = [];
